#!/usr/bin/env python3
"""
Generate userscript + extension artifacts from shared source modules.

Pipeline:
1) Parse userscript metadata header from src/userscript.header.js.
2) Build JS outputs by concatenating source modules from src/.
3) Write generated/extension/manifest.json from parsed metadata.
4) Optional ZIP for Chrome Web Store (CRX packaging disabled in this script).
"""

from __future__ import annotations

import argparse
import io
import json
import re
import sys
import zipfile
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parent.parent
SRC_DIR = REPO_ROOT / "src"
USERSCRIPT_HEADER_SOURCE = SRC_DIR / "userscript.header.js"
EXT_DIR = REPO_ROOT / "generated" / "extension"
CONTENT_OUT = EXT_DIR / "content.js"
MANIFEST_OUT = EXT_DIR / "manifest.json"
DIST_DIR = REPO_ROOT / "dist"
USERSCRIPT_OUT = DIST_DIR / "taiga-clean-view.userscript.js"
# Used only if you re-enable CRX generation below (see write_crx_artifact).
# SIGNING_KEY = REPO_ROOT / "keys" / "dev-signing-key.pem"

HEADER_RE = re.compile(
    r"(?P<header>// ==UserScript==\s*\n(?P<body>.*?)\n// ==/UserScript==)\s*\n?",
    re.DOTALL,
)
META_LINE_RE = re.compile(r"^\s*//\s*@(?P<key>\S+)\s*(?P<value>.*)$")

USERSCRIPT_BANNER = (
    "// Generated by scripts/build_extension.py from src/*.js\n"
    "// Do not edit by hand; run: python3 scripts/build_extension.py\n\n"
)
EXTENSION_BANNER = (
    "// Generated by scripts/build_extension.py from src/*.js\n"
    "// Do not edit by hand; run: python3 scripts/build_extension.py\n\n"
)


def read_text(path: Path) -> str:
    if not path.is_file():
        raise FileNotFoundError(f"Missing file: {path}")
    return path.read_text(encoding="utf-8")


def extract_header_and_meta(source: str) -> tuple[str, dict]:
    m = HEADER_RE.search(source)
    if not m:
        raise ValueError("Missing userscript metadata header block")

    header = m.group("header").strip() + "\n"
    block = m.group("body")
    meta: dict[str, object] = {"matches": []}

    for raw in block.splitlines():
        parsed = META_LINE_RE.match(raw)
        if not parsed:
            continue
        key = parsed.group("key").lower()
        value = parsed.group("value").strip()
        if key == "match":
            matches = meta["matches"]
            assert isinstance(matches, list)
            matches.append(value)
        elif key in ("name", "version", "description", "author"):
            meta[key] = value

    for need in ("name", "version", "description"):
        if not meta.get(need):
            raise ValueError(f"Userscript header missing @{need}")
    return header, meta


def expand_match_patterns(patterns: list[str]) -> list[str]:
    out: list[str] = []
    seen: set[str] = set()
    for p in patterns:
        p = p.strip()
        if not p or p in seen:
            continue
        seen.add(p)
        out.append(p)
        if p.endswith("/*"):
            bare = p[:-2]
            if bare and bare not in seen:
                seen.add(bare)
                out.append(bare)
    return out


def read_src(name: str) -> str:
    return read_text(SRC_DIR / name).strip() + "\n"


def render_userscript_js() -> str:
    return USERSCRIPT_BANNER + "\n".join(
        [
            read_src("storage.localstorage.js"),
            read_src("core.js"),
            read_src("entry.userscript.js"),
        ]
    )


def render_extension_js() -> str:
    return EXTENSION_BANNER + "\n".join(
        [
            read_src("storage.chrome.js"),
            read_src("core.js"),
            read_src("entry.extension.js"),
        ]
    )


def write_userscript(header: str, body_js: str) -> None:
    DIST_DIR.mkdir(parents=True, exist_ok=True)
    USERSCRIPT_OUT.write_text(f"{header}\n{body_js}", encoding="utf-8")


def write_extension_content(body_js: str) -> None:
    EXT_DIR.mkdir(parents=True, exist_ok=True)
    CONTENT_OUT.write_text(body_js, encoding="utf-8")


def write_manifest(meta: dict, matches: list[str]) -> None:
    manifest = {
        "manifest_version": 3,
        "name": meta["name"],
        "version": meta["version"],
        "description": meta["description"],
        "content_scripts": [
            {
                "matches": matches,
                "js": ["content.js"],
                "run_at": "document_idle",
                "all_frames": False,
            }
        ],
        "permissions": ["storage"],
    }
    if meta.get("author"):
        manifest["author"] = meta["author"]

    MANIFEST_OUT.write_text(
        json.dumps(manifest, indent=2, ensure_ascii=False) + "\n", encoding="utf-8"
    )


def extension_zip_bytes() -> bytes:
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w", compression=zipfile.ZIP_DEFLATED) as zf:
        zf.write(MANIFEST_OUT, arcname="manifest.json")
        zf.write(CONTENT_OUT, arcname="content.js")
    return buf.getvalue()


def write_crx_artifact(version: str, zip_bytes: bytes, key_path: Path) -> Path:
    scripts_dir = Path(__file__).resolve().parent
    if str(scripts_dir) not in sys.path:
        sys.path.insert(0, str(scripts_dir))

    try:
        from crx3_pack import pack_crx3
    except ImportError as exc:
        raise RuntimeError(
            "CRX packing needs scripts/crx3_pack.py and dependency "
            "'cryptography' (pip install -r scripts/requirements.txt)."
        ) from exc

    DIST_DIR.mkdir(parents=True, exist_ok=True)
    crx_path = DIST_DIR / f"taiga-clean-view-extension-{version}.crx"
    crx_path.write_bytes(pack_crx3(zip_bytes, key_path))
    return crx_path


def write_zip_artifact(version: str, zip_bytes: bytes) -> Path:
    DIST_DIR.mkdir(parents=True, exist_ok=True)
    zip_path = DIST_DIR / f"taiga-clean-view-extension-{version}.zip"
    zip_path.write_bytes(zip_bytes)
    return zip_path


def assert_invariants(userscript_js: str, extension_js: str, meta: dict) -> None:
    if "createTaigaCleanViewApp" not in userscript_js or "createTaigaCleanViewApp" not in extension_js:
        raise ValueError("Generated outputs are missing createTaigaCleanViewApp")
    if "createLocalStorageAdapter" not in userscript_js:
        raise ValueError("Userscript output is missing localStorage adapter")
    if "createChromeStorageAdapter" not in extension_js:
        raise ValueError("Extension output is missing chrome.storage adapter")
    if "localStorage" in extension_js:
        raise ValueError("Extension output still references localStorage")
    if "chrome.storage" in userscript_js:
        raise ValueError("Userscript output unexpectedly references chrome.storage")
    if not meta.get("version"):
        raise ValueError("Missing version in metadata")


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Build userscript + extension artifacts from src/"
    )
    parser.add_argument(
        "--zip",
        action="store_true",
        help="Also write dist/*.zip (Chrome Web Store upload format)",
    )
    args = parser.parse_args()

    source = read_text(USERSCRIPT_HEADER_SOURCE)
    header, meta = extract_header_and_meta(source)
    matches_raw = meta.get("matches") or []
    assert isinstance(matches_raw, list)
    matches = expand_match_patterns(matches_raw)
    if not matches:
        raise ValueError("No @match entries in userscript header")

    userscript_js = render_userscript_js()
    extension_js = render_extension_js()
    assert_invariants(userscript_js, extension_js, meta)

    write_userscript(header, userscript_js)
    write_extension_content(extension_js)
    write_manifest(meta, matches)

    version = str(meta["version"])
    zip_bytes = extension_zip_bytes()

    # CRX generation disabled: sideloading .crx is restricted on many Chromium-based
    # browsers (e.g. Brave). Use "Load unpacked" on generated/extension/ or --zip for the store.
    # To re-enable: restore SIGNING_KEY / --key and uncomment:
    # crx_path = write_crx_artifact(version, zip_bytes, REPO_ROOT / "keys" / "dev-signing-key.pem")
    # print(f"Wrote {crx_path.relative_to(REPO_ROOT)}")

    print(f"Wrote {USERSCRIPT_OUT.relative_to(REPO_ROOT)}")
    print(f"Wrote {CONTENT_OUT.relative_to(REPO_ROOT)}")
    print(f"Wrote {MANIFEST_OUT.relative_to(REPO_ROOT)}")

    if args.zip:
        zip_path = write_zip_artifact(version, zip_bytes)
        print(f"Wrote {zip_path.relative_to(REPO_ROOT)}")

    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except Exception as exc:
        print(f"error: {exc}", file=sys.stderr)
        raise SystemExit(1)
